### PR TITLE
add search method

### PR DESCRIPTION
**Pull request by faraazahmad**
solves issue #3

### CODE REVIEW

**Comment by btk** [comment]
Hey good job, but this is only changing the output, the assets.js file in the repository is a produced file with pre-require command. You should make changes in order to create this output in assets.js on index.js.

**Comment by faraazahmad** [comment]
im not sure what you mean by that
```
  let assetsFileContent = `// import this file for static assets
  let Obj = {
    ${slugArray.join(', ')}
  }
  export default Obj;
  `;
```

what do you want this to do?

**Comment by faraazahmad** [comment]
I suppose you want this code to generate the code in assets.js. I'll just close this PR and open one with changes on 1 Oct. That fine?

**Comment by btk** [comment]
Yes, that's great!

**Pull request closed without merging**
